[pytest]
pythonpath = .
addopts = --tracing=retain-on-failure --video=retain-on-failure --screenshot=only-on-failure
markers =
    smoke: fast, high-value tests
    regression: full test suite
    flaky: tests that are known to be flaky and may fail intermittently
playwright_visual_snapshots_path = tests/visual_snapshots
playwright_visual_snapshot_failures_path = tests/visual_snapshots/failures