name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v7

      - name: "Setup python"
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: "Install dependencies"
        run: pip install -r requirements.txt

      - name: "Install Playwright browsers"
        run: playwright install --with-deps

      - name: "Run tests"
        run: pytest tests/ --browser ${{ matrix.browser }} --junitxml=report.xml --html=report.html --self-contained-html
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          STANDARD_USER: ${{ secrets.STANDARD_USER }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}

      - name: "Publish test report using dorny"
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: "Pytest Results (${{ matrix.browser }})"
          path: reportDorny.xml
          reporter: java-junit

      - name: "Upload junit test report"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report-${{ matrix.browser }}
          path: reportJUNIT.xml

      - name: "Upload HTML report"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report-${{ matrix.browser }}
          path: reportHTML.html

      - name: "Upload failure artifacts"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces-${{ matrix.browser }}
          path: test-results/
